name: Generate API client

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  lint:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: OpenAPI Lint Checks
       uses: nwestfall/openapi-action@v1.0.2
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         file: openapi.json

  build:
    needs: 
      - lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Generate API client
      run: php vendor/bin/jane-openapi generate
    
    # Commit modified files
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "auto: generate client"

    # Push changes
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
