name: Lint OpenAPI spec

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  lint:
     runs-on: ubuntu-latest
     steps:
     - name: OpenAPI Lint Checks
       uses: nwestfall/openapi-action@v1.0.2
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         file: openapi.json